69 implementing password recovery
Project-Stage-Academy/UA1303 pull request #100
Opened 2024-12-17 16:10 UTC by IraMladanovych02

- Added a /password/reset/ endpoint to handle password reset requests with CAPTCHA validation.
- Integrated rate limiting to prevent brute-force attempts.
- Configured email sending via Gmail SMTP to deliver password reset links.
- Customized email template (password_reset.html) to provide user-friendly instructions.
- Integrated ReCaptcha to prevent automated misuse of the reset endpoint.
- Ensured all tokens generated for password resets are time-sensitive and expire securely.

2024-12-17 19:14 UTC, BasilJaworski commented on forum/templates/users/password_reset.html
> +    <h2>Відновлення пароля</h2>
Just recomendation(If not nessesary then just skip this comment)

Use main tag for better html structure, wrap like:
<body>
    <main>
        <-- content -->
    </main>
</body>

2024-12-17 19:19 UTC, BasilJaworski commented on forum/templates/users/password_reset.html
> +    <meta charset="UTF-8">
Just recommendation(If not necessary then just skip this comment)

Add meta tag to ensure the page is responsive on mobile devices
<meta name="viewport" content="width=device-width, initial-scale=1.0">

2024-12-17 19:21 UTC, BasilJaworski approved these changes
Added two comments how to improve the html. Just recommendation)

2024-12-18 11:32 UTC, mehalyna requested changes

2024-12-18 11:32 UTC, mehalyna commented on forum/users/email.py
Currently, you are determining the protocol (http or https) based on the request's security. While this is correct, there can be scenarios where the request may not properly reflect the actual protocol, particularly behind reverse proxies or load balancers.
Use `SECURE_SSL_REDIRECT` from settings, it is better to explicitly set the protocol in your configuration.
```
from django.conf import settings

class PasswordResetEmail(email.PasswordResetEmail):
    template_name = "email/password_reset.html"

    def get_context_data(self):
        context = super().get_context_data()
        context["domain"] = get_current_site(self.context["request"]).domain
        context["protocol"] = "https" if settings.SECURE_SSL_REDIRECT else "http"
        return context
```

2024-12-18 11:32 UTC, mehalyna commented on forum/users/email.py
> +        context["domain"] = get_current_site(self.context["request"]).domain
Using `get_current_site` works well for dynamic domain detection. However, in production, it is often cleaner and more secure to explicitly define the domain in environment variables.
In `settings.py`:
```
DOMAIN_NAME = os.getenv("DOMAIN_NAME", "localhost")
```

2024-12-19 21:51 UTC, djmelyk-debelyk approved these changes

2024-12-20 04:51 UTC, mehalyna approved these changes

2024-12-20 12:03 UTC, merged