Startup profiles filter-search-ordering tests
Project-Stage-Academy/UA1303 pull request #135
Opened 2024-12-29 23:50 UTC by maksym-derkach

Fix technical debt in StartupProfile filtering-search-ordering functionality
[#134](https://github.com/Project-Stage-Academy/UA1303/issues/134)

2024-12-30 09:26 UTC, mehalyna requested changes

2024-12-30 09:26 UTC, mehalyna commented on forum/profiles/tests.py
Tests for filtering, searching, and sorting share similar logic. To avoid duplication, consider creating helper methods.
_Example:_
```
def perform_get_request_and_assert(self, url, field, expected_value):
    response = self.client.get(url)
    self.assertEqual(response.status_code, status.HTTP_200_OK)
    self.assertGreater(len(response.data), 0)
    self.assertTrue(all(expected_value in startup[field] for startup in response.data))
```
You can then refactor individual tests to:
```
def test_filter_by_industry(self):
    url = f"{self.startup_url}?industry=Technology"
    self.perform_get_request_and_assert(url, 'industry', 'Technology')
```

2024-12-30 09:26 UTC, mehalyna commented on forum/profiles/tests.py
Add test scenarios where multiple filters are applied simultaneously (e.g., `industry=Technology&country=USA`).
_Example:_
```
def test_filter_by_industry_and_country(self):
    url = f"{self.startup_url}?industry=Technology&country=USA"
    response = self.client.get(url)
    self.assertEqual(response.status_code, status.HTTP_200_OK)
    self.assertTrue(all(
        startup['industry'] == 'Technology' and startup['country'] == 'USA'
        for startup in response.data
    ))
```

2024-12-30 09:26 UTC, mehalyna commented on forum/profiles/tests.py
Include edge cases for sorting, such as when profiles have the same `company_name` or `created_at` values.
_Example:_
```
def test_sort_by_company_name_with_duplicates(self):
    # Create duplicate company names
    StartupProfile.objects.create(
        user=self.users[1],
        company_name='Duplicate Name',
        industry='AI',
        size='Large',
        country='USA',
        city='New York',
    )
    StartupProfile.objects.create(
        user=self.users[2],
        company_name='Duplicate Name',
        industry='AI',
        size='Small',
        country='USA',
        city='San Francisco',
    )
    url = f"{self.startup_url}?ordering=company_name"
    response = self.client.get(url)
    self.assertEqual(response.status_code, status.HTTP_200_OK)
```

2024-12-30 09:26 UTC, mehalyna commented on forum/profiles/tests.py
Add a test to ensure unauthorized users cannot access the API.
_Example:_
```
def test_unauthorized_access(self):
    url = f"{self.startup_url}?industry=Technology"
    response = self.client.get(url)
    self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
```

2024-12-30 09:26 UTC, mehalyna commented on forum/profiles/tests.py
Instead of manually creating objects in setUp, consider using libraries like [Factory Boy](https://factoryboy.readthedocs.io/) for more scalable and maintainable test data generation.
_Example:_
```
from factory import Faker, SubFactory
import factory.django

class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User
    email = Faker('email')
    password = 'securepassword'

class StartupProfileFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = StartupProfile
    user = SubFactory(UserFactory)
    company_name = Faker('company')
    industry = Faker('word')
    country = Faker('country')
    city = Faker('city')
```

2024-12-30 22:00 UTC, maksym-derkach commented on forum/profiles/tests.py
Done

2024-12-31 13:24 UTC, maksym-derkach commented on forum/profiles/tests.py
Done

2024-12-31 13:41 UTC, maksym-derkach commented on forum/profiles/tests.py
Done

2024-12-31 22:54 UTC, maksym-derkach commented on forum/profiles/tests.py
Done

2025-01-01 16:08 UTC, SergeKry approved these changes

2025-01-01 19:17 UTC, mehalyna approved these changes

2025-01-02 18:52 UTC, olexiyko approved these changes

2025-01-02 20:37 UTC, merged