Set Up JWT Authorization in Django #73
Project-Stage-Academy/UA1303 pull request #96
Opened 2024-12-15 00:14 UTC by SergeKry

2024-12-15 11:33 UTC, mehalyna requested changes

2024-12-15 11:33 UTC, mehalyna commented on forum/forum/settings.py
> +        'rest_framework_simplejwt.authentication.JWTAuthentication',
You may explicitly define DEFAULT_AUTHENTICATION_CLASSES for clarity:
```
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}
```

2024-12-15 11:33 UTC, mehalyna commented on forum/forum/settings.py
> +    'BLACKLIST_AFTER_ROTATION': False,
Consider setting `BLACKLIST_AFTER_ROTATION` to `True` if you want to invalidate old refresh tokens after they are used.
If `BLACKLIST_AFTER_ROTATION` is `True`, ensure `rest_framework_simplejwt.token_blacklist` should be added to `INSTALLED_APPS`:
```
INSTALLED_APPS += [
    'rest_framework_simplejwt.token_blacklist',
]
```

2024-12-15 11:33 UTC, mehalyna commented on forum/forum/settings.py
> +    'SIGNING_KEY': SECRET_KEY,
Use a separate signing key for better security in production:
```
SIMPLE_JWT = {
    ...
    'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY', SECRET_KEY),
    ...
}
```

2024-12-16 04:47 UTC, mehalyna approved these changes

2024-12-16 09:45 UTC, IraMladanovych02 approved these changes

2024-12-16 22:36 UTC, ne0ascorbinka approved these changes

2024-12-16 22:36 UTC, ne0ascorbinka commented on forum/forum/urls.py
> +    re_path(r'^auth/', include('djoser.urls')),
Everything above seems legit, the only thing is idk if other links beside djoser.urls.jwt are necessary, but idk

2024-12-17 01:04 UTC, merged