#35 initial/integrate logging system
Project-Stage-Academy/UA1303 pull request #97
Opened 2024-12-15 11:31 UTC by danylkoltak

logging settings in settings.py. forum activities are saved in console and forum.log, database activities are saved in console and database.log.

2024-12-15 14:54 UTC, djmelyk-debelyk approved these changes

2024-12-16 13:22 UTC, VovaD199 requested changes

2024-12-16 13:22 UTC, VovaD199 commented on forum/forum/settings.py
> +
If access to the file system is restricted, os.makedirs() may throw an error. Add exception handling:
try:
    os.makedirs(LOG_DIR, exist_ok=True)
except OSError as e:
    raise RuntimeError(f"Failed to create log directory {LOG_DIR}: {e}")

2024-12-17 15:00 UTC, VovaD199 approved these changes

2024-12-17 15:45 UTC, olexiyko approved these changes

2024-12-17 18:19 UTC, merged